env:
  global:
    - REPO_DIR=.
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - PLAT=x86_64

install: 
  - git clone https://github.com/matthew-brett/multibuild
  - . multibuild/common_utils.sh
  - . multibuild/travis_steps.sh
  - before_install 
  # - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $REPO_DIR $PLAT
script: 
  - install_run $PLAT

after_success:
  - ./deploy.sh

    
matrix:
  include:

    - os: linux
    
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
 
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9

    - os: osx
      osx_image: xcode12.3
 
    - os: osx
      osx_image: xcode12.3
      env:
        - MB_PYTHON_VERSION=3.6
 
    - os: osx
      osx_image: xcode12.3
      env:
        - MB_PYTHON_VERSION=3.7
 
     - os: osx
      osx_image: xcode12.3
      env:
        - MB_PYTHON_VERSION=3.8

    - os: osx
      osx_image: xcode12.3
      env:
        - MB_PYTHON_VERSION=3.9
 
